index:
   path: /
   controller: App\Controller\HomeController::index
book:
    path:       /book/{id}
    controller: App\Controller\BookController::show
ajax_books_fetch:
    path:       /ajax_books_fetch
    controller: App\Controller\HomeController::getBooks