#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_post_show:
    path:       /api/posts/{id}
    controller: App\Controller\BookController::show
    methods:    GET|HEAD